name: CI

on: [push, pull_request]

jobs:
  build:
    name: Build & test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          check-latest: true

      - name: Coursier cache
        uses: coursier/cache-action@v6

      #- name: Check formatting
      #  run: sbt fixCheck
      - name: Compile and test
        run: sbt +test

  ci-passed:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: ':'
